version: "2.3"
services:
  mysql-host:
    image: mysql:5.6
    volumes:
      - type: bind
        source: ./database
        target: /docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=YzB3UC1t1XrF
      - MYSQL_DATABASE=stocker
      - MYSQL_USER=eep
      - MYSQL_PASSWORD=YzB3UC1t1XrF
    ports:
      - 3306:3306
    networks:
      - stocker-network
  stocker:
    image: domocles/stocker
    depends_on:
      - mysql-host
    ports:
      - 80:8080
    environment:
      - DATABASE_HOST=mysql-host
      - DATABASE_USER=eep
      - DATABASE_PASSWORD=YzB3UC1t1XrF
      - DATABASE_NAME=stocker
      - DATABASE_PORT=3306
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - stocker-network
networks:
  stocker-network:
    driver: bridge